language: python
dist: xenial
python: "3.7"
sudo: false
addons:
  apt:
    packages:
    - gdal-bin
    - libproj-dev
    - libhdf5-serial-dev
    - libgdal-dev
    - libatlas-dev
    - libatlas-base-dev
    - gfortran
install:
  - pip install -r requirements.txt
before_script:
  - psql -c "CREATE DATABASE codeforbaltimore;" -U postgres
script:
  - make lint
  - make coverage
services:
  - postgresql
