language: python
dist: xenial
python: "3.7"
sudo: true
addons:
  apt:
    packages:
    - gdal-bin
    - libgdal-dev
install:
  - export CPLUS_INCLUDE_PATH=/usr/include/gdal
  - export C_INCLUDE_PATH=/usr/include/gdal
  - pip install --no-use-wheel -r requirements.txt
before_script:
  - psql -c "CREATE DATABASE codeforbaltimore;" -U postgres
script:
  - make lint
  - make coverage
services:
  - postgresql
