# Generated by Django 2.2.1 on 2019-05-23 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmergencyPoliceCalls',
            fields=[
                ('record_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('call_number', models.CharField(max_length=100)),
                ('call_date_time', models.DateTimeField()),
                ('priority', models.CharField(max_length=30)),
                ('district', models.CharField(max_length=10)),
                ('description', models.TextField()),
                ('incident_location', models.TextField()),
                ('zipcode', models.CharField(max_length=10)),
                ('neighborhood', models.CharField(max_length=100)),
                ('police_district', models.CharField(max_length=30)),
                ('police_post', models.CharField(max_length=10)),
                ('council_district', models.IntegerField()),
                ('sheriff_districts', models.CharField(max_length=20)),
                ('community_statistical_areas', models.TextField()),
                ('census_tracts', models.TextField()),
                ('vri_zones', models.CharField(max_length=100)),
                ('location', models.TextField()),
                ('census_neighborhoods_2010', models.TextField()),
                ('census_wards_precincts', models.TextField()),
                ('zip_codes', models.TextField()),
            ],
        ),
    ]
