# Generated by Django 2.2.1 on 2019-05-31 04:33

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Arrests',
            fields=[
                ('arrest_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('age', models.IntegerField()),
                ('sex', models.CharField(max_length=10)),
                ('race', models.CharField(max_length=10)),
                ('arrest_date_time', models.DateTimeField(db_index=True)),
                ('arrest_date', models.DateField()),
                ('arrest_time', models.TimeField()),
                ('arrest_location', models.TextField()),
                ('incident_offense', models.CharField(max_length=100)),
                ('incident_location', models.TextField()),
                ('charge', models.CharField(max_length=100)),
                ('charge_description', models.TextField()),
                ('district', models.CharField(max_length=30)),
                ('post', models.CharField(max_length=30)),
                ('neighborhood', models.CharField(max_length=100)),
                ('longitude', models.FloatField()),
                ('latitude', models.FloatField()),
                ('gps_coordinates', django.contrib.gis.db.models.fields.PointField(db_index=True, srid=4326)),
                ('location', models.TextField()),
                ('census_neighborhoods_2010', models.TextField()),
                ('census_wards_precincts', models.TextField()),
                ('zip_codes', models.TextField()),
            ],
            options={
                'ordering': ['-arrest_id'],
            },
        ),
        migrations.CreateModel(
            name='EmergencyPoliceCalls',
            fields=[
                ('record_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('call_number', models.CharField(max_length=100)),
                ('call_date_time', models.DateTimeField(db_index=True)),
                ('priority', models.CharField(max_length=30)),
                ('district', models.CharField(max_length=10)),
                ('description', models.TextField()),
                ('incident_location', models.TextField()),
                ('zipcode', models.CharField(max_length=10)),
                ('neighborhood', models.CharField(max_length=100)),
                ('police_district', models.CharField(max_length=30)),
                ('police_post', models.CharField(max_length=10)),
                ('council_district', models.IntegerField()),
                ('sheriff_districts', models.CharField(max_length=20)),
                ('community_statistical_areas', models.TextField()),
                ('census_tracts', models.TextField()),
                ('vri_zones', models.CharField(max_length=100)),
                ('location', models.TextField()),
                ('gps_coordinates', django.contrib.gis.db.models.fields.PointField(db_index=True, srid=4326)),
                ('census_neighborhoods_2010', models.TextField()),
                ('census_wards_precincts', models.TextField()),
                ('zip_codes', models.TextField()),
            ],
            options={
                'ordering': ['-record_id'],
            },
        ),
        migrations.CreateModel(
            name='VictimBasedCrime',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('checksum', models.CharField(max_length=32, unique=True)),
                ('crime_date_time', models.DateTimeField(db_index=True)),
                ('crime_date', models.DateField()),
                ('crime_time', models.TimeField()),
                ('crime_code', models.CharField(max_length=30)),
                ('location', models.TextField()),
                ('description', models.TextField()),
                ('inside_outside', models.CharField(max_length=30)),
                ('weapon', models.CharField(max_length=30)),
                ('post', models.CharField(max_length=30)),
                ('district', models.CharField(max_length=30)),
                ('neighborhood', models.CharField(max_length=100)),
                ('longitude', models.FloatField()),
                ('latitude', models.FloatField()),
                ('gps_coordinates', django.contrib.gis.db.models.fields.PointField(db_index=True, srid=4326)),
                ('location_1', models.CharField(max_length=100)),
                ('premise', models.CharField(max_length=100)),
                ('vri_name', models.CharField(max_length=100)),
                ('total_incidents', models.IntegerField()),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
