# Generated by Django 2.2.1 on 2019-05-29 22:19

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publicsafety', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Arrests',
            fields=[
                ('arrest_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('age', models.IntegerField()),
                ('sex', models.CharField(max_length=10)),
                ('race', models.CharField(max_length=10)),
                ('arrest_date_time', models.DateTimeField(db_index=True)),
                ('arrest_date', models.DateField()),
                ('arrest_time', models.TimeField()),
                ('arrest_location', models.TextField()),
                ('incident_offense', models.CharField(max_length=100)),
                ('incident_location', models.TextField()),
                ('charge', models.CharField(max_length=100)),
                ('charge_description', models.TextField()),
                ('district', models.CharField(max_length=30)),
                ('post', models.CharField(max_length=10)),
                ('neighborhood', models.CharField(max_length=100)),
                ('longitude', models.FloatField()),
                ('latitude', models.FloatField()),
                ('gps_coordinates', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('location', models.TextField()),
                ('census_neighborhoods_2010', models.TextField()),
                ('census_wards_precincts', models.TextField()),
                ('zip_codes', models.TextField()),
            ],
        ),
    ]
